name: Monitor Changes

on:
  schedule:
    - cron: "23 4 * * *"

jobs:
  release:
    name: Monitor Changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "20"
      - name: Install dependencies
        run: pnpm install
      - name: Run the tests
        run: pnpm test ./test/gcp.schema.test.ts
